### ISSUE TITLE
Hi! Thank you in advance... :D

### ISSUE THREAD

**Issue by Zapplusey** [doombubbles/card-monkey#6]
Hi Doombubbles! I really appreciate your work, and I would like to know where are you getting the information to modding in such an advanced way? (besides the BTD 6 mod helper guide, and the literally SINGLE tutorial that's available on YouTube).
I know it may be a little overbearing, but could you please explain to me how to debug my mod (it's for towers), there are 0 errors when I run BTD6 with it, but when I start a round, the shop menu doesn't have any towers..
[Supreme.zip](https://github.com/doombubbles/card-monkey/files/9366662/Supreme.zip)
.

**Comment by doombubbles** [comment]
Lol well as the author of the Mod Helper guide I'm not getting info from there so much as putting it there haha. My knowledge comes from having existing experience with C# and Unity, knowing how to navigate the decompiled code, and just having been doing this hobby for like a year and half.

As to your tower, your two immediate issues are that your `MageMonkey_Portrait.png` and `MageMonkey_Icon.png` should instead be `MageMonkey-Portrait.png` and `MageMonkey-Icon.png` (using dashes), and that you should not be doing 

```
towerModel.name = "MageMonkey";
``` 

in your `ModifyBaseTowerModel` method. That "name" field already gets set to the correct value by Mod Helper.
